pub mod attendance_dashboard;
pub mod attendance_page;
pub mod detail_page;
pub mod faker_page;
pub mod guardian_contact_details;
pub mod message_dashboard;
pub mod message_page;
pub mod test_page;
pub mod unknown_contact_details;
